# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager with bare repo support"
  homepage "https://github.com/raisedadead/wt"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"
  manpage "man/wt.1"
  bash_completion "completions/wt.bash"
  zsh_completion "completions/_wt"
  fish_completion "completions/wt.fish"

  on_macos do
    on_intel do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_darwin_amd64.tar.gz"
      sha256 "e5113ce66966395c9831d9e4a4a2d96e874051877edbbf687b4ca0ec2086fb6d"
    end
    on_arm do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_darwin_arm64.tar.gz"
      sha256 "244a8e59e60cac5088ff26d59131581dffcbc250fad45142b538045d4bed14e4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_linux_amd64.tar.gz"
      sha256 "8f7d38e99ca64700e915330ad53403c18a4a4ec4db26269117a12f37d93ac49e"
    end
    on_arm do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_linux_arm64.tar.gz"
      sha256 "fb1f86a8e2a196c3e44c8e0dc50680371e237d723b090ca4fd947000363960ff"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    system_command "/bin/ln", args: ["-sf", "#{staged_path}/wt", "#{staged_path}/git-wt"]
  end

  # No zap stanza required
end
