# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager with bare repo support"
  homepage "https://github.com/raisedadead/wt"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"
  manpage "man/wt.1"
  bash_completion "completions/wt.bash"
  zsh_completion "completions/_wt"
  fish_completion "completions/wt.fish"

  on_macos do
    on_intel do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_darwin_amd64.tar.gz"
      sha256 "0e9d04986173ef00917596bad9d9a35f133b6e5b983da91b0fde0bf73d7b7a7e"
    end
    on_arm do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_darwin_arm64.tar.gz"
      sha256 "0b80548478ce25e1eb041c0cadfc98919f9ea35b69e2ea39ad3dcc40d0b02702"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_linux_amd64.tar.gz"
      sha256 "5edd01cd5842db5466bacb83df457ac8a8989db7168ccef2c8b9c4f40cf40e65"
    end
    on_arm do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_linux_arm64.tar.gz"
      sha256 "0855a0bbe7c9c1a64554a95c62d5771682484fa5f34802293c1010b3159beaaa"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    system_command "/bin/ln", args: ["-sf", "#{staged_path}/wt", "#{staged_path}/git-wt"]
  end

  # No zap stanza required
end
