# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager with bare repo support"
  homepage "https://github.com/raisedadead/wt"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"
  manpage "man/wt.1"
  bash_completion "completions/wt.bash"
  zsh_completion "completions/_wt"
  fish_completion "completions/wt.fish"

  on_macos do
    on_intel do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_darwin_amd64.tar.gz"
      sha256 "e0a8641e87ca74f80616af1fcb367c8b6476699f76dc22f825731d6323ef89c3"
    end
    on_arm do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_darwin_arm64.tar.gz"
      sha256 "d38d63950da3f4c046363bab710298be87fa3086ee7ee2ec83d09ba9a758bfad"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_linux_amd64.tar.gz"
      sha256 "07d879bedd3968ec715f16ade6c91e5553b83fe9e0b55ecd7097e53d2d1a3a08"
    end
    on_arm do
      url "https://github.com/raisedadead/wt/releases/download/v#{version}/wt_linux_arm64.tar.gz"
      sha256 "9175293c8423f88f2449115d5cc2dcb9dda079f144910c8125baccf7e8d254ce"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    system_command "/bin/ln", args: ["-sf", "#{staged_path}/wt", "#{staged_path}/git-wt"]
  end

  # No zap stanza required
end
